import { defineConfig } from 'vite';

export default defineConfig({
  build: {
    target: 'node20',
    outDir: 'dist',
    lib: {
      entry: './src/app.ts',
      name: 'app',
      formats: ['cjs'],
      fileName: () => 'src/app.cjs',
    },
    rollupOptions: {
      external: [
        // Node.js built-ins
        'fs',
        'path',
        'crypto',
        'os',
        'util',
        'events',
        'stream',
        'url',
        'querystring',
        'http',
        'https',
        'net',
        'tls',
        'zlib',
        'buffer',
        'child_process',
        'cluster',
        'dgram',
        'dns',
        'domain',
        'readline',
        'repl',
        'string_decoder',
        'timers',
        'tty',
        'vm',
        'worker_threads',
        'perf_hooks',
        'async_hooks',
        'inspector',
        // Dependencies
        'express',
        '@prisma/client',
        'kuromoji',
        'csv-parser',
        'dotenv',
      ],
    },
    minify: false,
    sourcemap: true,
    emptyOutDir: false,
  },
});
