name: 'Build Sphinx Documentation'
description: 'Builds Sphinx documentation from a specified directory.'

inputs:
  working-directory:
    description: 'Path to the working directory for Sphinx.'
    required: false
    default: 'docs/sphinx'

runs:
  using: 'composite'
  steps:
    - name: Install Sphinx Python dependencies
      run: uv pip install -r ${{ inputs.requirements-file }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Activate venv
      run: source .venv/bin/activate
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Build Sphinx Docs
      run: sphinx-build -b html . "${GITHUB_WORKSPACE}/mkdocs_content/sphinx/"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
