name: Deploy Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install uv
        run: pip install uv
      - name: Install MkDocs Python dependencies
        run: uv pip install -r docs/requirements.txt
      - name: Build Sphinx Documentation
        uses: ./.github/actions/build-sphinx
        with:
          working-directory: docs/sphinx
          requirements-file: docs/sphinx/requirements.txt
      - name: Setup Node.js, pnpm, and Generate Typedoc
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version-file: package.json
          working-directory: .
      - name: Prepare MkDocs content directories
        run: |
          mkdir -p docs/mkdocs_content/sphinx_docs
          mkdir -p docs/mkdocs_content/typedoc_docs
      - name: Copy Sphinx Docs to MkDocs content
        run: cp -r docs/sphinx/_build/html/. docs/mkdocs_content/sphinx_docs/
      - name: Copy TypeDoc Docs to MkDocs content
        run: cp -r docs/typedoc/. docs/mkdocs_content/typedoc_docs/
      - name: Build MkDocs
        run: mkdocs build -f docs/mkdocs.yml
      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force
