name: Deploy Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install uv
        run: pip install uv
      - name: Set up virtual environment
        run: uv venv
      - name: Install MkDocs Python dependencies
        run: uv pip install -r docs/requirements.txt
      - name: Build Sphinx Documentation
        uses: ./.github/actions/build-sphinx
        with:
          working-directory: docs/sphinx
      - name: Install pnpm
        run: npm install -g pnpm@latest-10
      - name: Setup Node.js, pnpm, and Generate Typedoc
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version-file: package.json
          working-directory: .
      - name: Build MkDocs
        run: |
          source .venv/bin/activate
          mkdocs build -f docs/mkdocs.yml
      - name: Deploy MkDocs
        run: |
          source .venv/bin/activate
          mkdocs gh-deploy --force -f docs/mkdocs.yml
